version: '3.5'
services:
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  gpu-vishal:
    image: nvcr.io/nvidia/tensorflow:23.09-tf2-py3
    environment:
      - JUPYTER_TOKEN=Password
    command: sh -c "pip install jupyter && pip install jupyterlab && jupyter lab --allow-root --ip=0.0.0.0"
    ports:
      - "9002:8888"
    volumes:
      - /home/vishal:/workspace/:rw
    container_name: vishal
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "test -s `which nvidia-smi` && nvidia-smi || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
