version: '3.9'

services:
  gpu-vishal:
    image: nvcr.io/nvidia/tensorflow:23.09-tf2-py3
    container_name: vishal
    restart: always
    ports:
      - 9002:8888
    volumes:
      - /home/vishal:/workspace
    environment:
      - JUPYTER_TOKEN=Password
    command: sh -c "pip install jupyter jupyterlab && jupyter lab --allow-root --ip=0.0.0.0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
