FROM nvidia/cuda:12.1.1-base-ubuntu22.04

ENV DEBIAN_FRONTEND noninteractive
ENV TZ Etc/UTC
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib64
ENV PKG_CONFIG_PATH /usr/local/lib/pkgconfig/
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all
ENV FFMPEG_BINARY /usr/local/bin/ffmpeg

RUN apt -y update && \
    apt install -y \
    libass-dev libfdk-aac-dev librtmp-dev libssl-dev libvdpau1 \
    libvorbis-dev libvpx-dev libx264-dev libx265-dev && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt -y update && \
    apt install -y \
    build-essential software-properties-common net-tools tmux \ 
    neovim wget unzip xvfb curl cmake gcc git libc6 libc6-dev \
    libtool nasm openssh-server nvidia-cuda-toolkit \
    yasm && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /src

RUN git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git && \
    cd nv-codec-headers && \
    make && make install

RUN git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg/ && \
    cd /src/ffmpeg && \
    ./configure \
    --prefix="/usr/local" \
    --disable-debug \
    --enable-cuda \
    --enable-cuda-llvm \
    --enable-cuda-nvcc \
    --enable-cuvid \
    --enable-ffnvcodec \
    --enable-gpl \
    --enable-libass \
    --enable-libfdk-aac \
    --enable-libnpp \
    --enable-librtmp \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libx264 \
    --enable-libx265 \
    --enable-nonfree \
    --enable-nvenc \
    --enable-opencl \
    --enable-openssl \
    --enable-pic \
    --enable-static \
    --extra-cflags="-I/usr/local/nvidia/include/" \
    --extra-ldflags="-L/usr/local/nvidia/lib64/" && \
    make -j$(nproc) && make install

RUN apt -y update && apt-get -y install \
    python3.10 \
    python3-pip

RUN pip3 install --upgrade pip

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

WORKDIR /workspace

RUN mkdir /var/run/sshd
RUN echo 'root:password' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Optional: Uncomment this line to disable password authentication in SSH
# RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config

CMD ["/usr/sbin/sshd", "-D"]
